# Generated by Django 5.2.2 on 2025-06-12 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('technology', models.CharField(choices=[('2G', '2G'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G')], max_length=10)),
                ('signal_type', models.CharField(choices=[('quantity', 'Quantity'), ('quality', 'Quality')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ThresholdLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=20)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='threshold.thresholdparameter')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('parameter', 'level')},
            },
        ),
    ]
