# Generated by Django 5.2.2 on 2025-06-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thresholdlevel',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
