# Generated by Django 5.2.2 on 2025-08-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalTest2G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('technology', models.CharField(choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('plmn_id', models.CharField(max_length=10)),
                ('cell_id', models.BigIntegerField()),
                ('arfcn', models.IntegerField(blank=True, null=True)),
                ('band', models.IntegerField(blank=True, null=True)),
                ('lac', models.IntegerField()),
                ('rxlev', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalTest3G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('technology', models.CharField(choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('plmn_id', models.CharField(max_length=10)),
                ('cell_id', models.BigIntegerField()),
                ('arfcn', models.IntegerField(blank=True, null=True)),
                ('band', models.IntegerField(blank=True, null=True)),
                ('lac', models.IntegerField()),
                ('rscp', models.FloatField()),
                ('node_id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalTest4G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('technology', models.CharField(choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('plmn_id', models.CharField(max_length=10)),
                ('cell_id', models.BigIntegerField()),
                ('arfcn', models.IntegerField(blank=True, null=True)),
                ('band', models.IntegerField(blank=True, null=True)),
                ('tac', models.IntegerField()),
                ('rsrp', models.FloatField()),
                ('rsrq', models.FloatField(blank=True, null=True)),
                ('node_id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalTest5G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('technology', models.CharField(choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('plmn_id', models.CharField(max_length=10)),
                ('cell_id', models.BigIntegerField()),
                ('arfcn', models.IntegerField(blank=True, null=True)),
                ('band', models.IntegerField(blank=True, null=True)),
                ('tac', models.IntegerField()),
                ('rsrp', models.FloatField()),
                ('rsrq', models.FloatField(blank=True, null=True)),
                ('node_id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
