# Generated by Django 5.2.2 on 2025-08-19 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalTest2G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('technology', models.CharField(choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('plmn_id', models.CharField(max_length=10)),
                ('cell_id', models.BigIntegerField()),
                ('arfcn', models.IntegerField(blank=True, null=True)),
                ('band', models.IntegerField(blank=True, null=True)),
                ('lac', models.IntegerField()),
                ('rxlev', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_2g', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalTest3G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('technology', models.CharField(choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('plmn_id', models.CharField(max_length=10)),
                ('cell_id', models.BigIntegerField()),
                ('arfcn', models.IntegerField(blank=True, null=True)),
                ('band', models.IntegerField(blank=True, null=True)),
                ('lac', models.IntegerField()),
                ('rscp', models.FloatField()),
                ('node_id', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_3g', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalTest4G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('technology', models.CharField(choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('plmn_id', models.CharField(max_length=10)),
                ('cell_id', models.BigIntegerField()),
                ('arfcn', models.IntegerField(blank=True, null=True)),
                ('band', models.IntegerField(blank=True, null=True)),
                ('tac', models.IntegerField()),
                ('rsrp', models.FloatField()),
                ('rsrq', models.FloatField(blank=True, null=True)),
                ('node_id', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_4g', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalTest5G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('technology', models.CharField(choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('plmn_id', models.CharField(max_length=10)),
                ('cell_id', models.BigIntegerField()),
                ('arfcn', models.IntegerField(blank=True, null=True)),
                ('band', models.IntegerField(blank=True, null=True)),
                ('tac', models.IntegerField()),
                ('rsrp', models.FloatField()),
                ('rsrq', models.FloatField(blank=True, null=True)),
                ('node_id', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_5g', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
