# Generated by Django 5.2.2 on 2025-06-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaltest2g',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='signaltest3g',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='signaltest4g',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='signaltest5g',
            name='generation',
        ),
        migrations.AddField(
            model_name='signaltest2g',
            name='rac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signaltest2g',
            name='technology',
            field=models.CharField(blank=True, choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='signaltest3g',
            name='technology',
            field=models.CharField(blank=True, choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='signaltest4g',
            name='technology',
            field=models.CharField(blank=True, choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='signaltest5g',
            name='technology',
            field=models.CharField(blank=True, choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signaltest2g',
            name='rxlev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signaltest3g',
            name='ecn0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signaltest4g',
            name='rsrq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signaltest5g',
            name='rsrq',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
