# Generated by Django 5.2.2 on 2025-06-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellinfo', '0002_remove_signaltest2g_generation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaltest2g',
            name='technology',
            field=models.CharField(choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20),
        ),
        migrations.AlterField(
            model_name='signaltest3g',
            name='technology',
            field=models.CharField(choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20),
        ),
        migrations.AlterField(
            model_name='signaltest4g',
            name='technology',
            field=models.CharField(choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20),
        ),
        migrations.AlterField(
            model_name='signaltest5g',
            name='technology',
            field=models.CharField(choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('LTE-Adv', 'LTE Advanced'), ('5G', '5G')], max_length=20),
        ),
    ]
