# Generated by Django 5.2.2 on 2025-06-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellinfo', '0003_alter_signaltest2g_technology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaltest2g',
            name='node_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signaltest3g',
            name='node_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signaltest4g',
            name='node_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signaltest5g',
            name='node_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
