# Generated by Django 5.2.2 on 2025-07-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellinfo', '0004_signaltest2g_node_id_signaltest3g_node_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaltest2g',
            name='node_id',
        ),
        migrations.RemoveField(
            model_name='signaltest2g',
            name='rac',
        ),
        migrations.RemoveField(
            model_name='signaltest3g',
            name='ecn0',
        ),
    ]
