# Generated by Django 5.2.2 on 2025-06-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNSTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('dns_response_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HTTPDownloadTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('download_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HTTPUploadTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('upload_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('ping_response_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SMSTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('timestamp_sent', models.DateTimeField()),
                ('timestamp_delivery', models.DateTimeField()),
                ('delivery_duration', models.FloatField()),
                ('message_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WebResponseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('web_response_time', models.FloatField()),
            ],
        ),
    ]
